# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Get certificates and sign provisioning profile"
  lane :code_sign do
    get_certificates
    get_provisioning_profile
  end

  desc "Runs all the tests"
  lane :tests do
    run_tests(scheme: "BayAreaCommute")
  end

end


